In [1]:
import numpy as np
from tinynn import *

In [2]:
# 0 0 -> 0
# 0 1 -> 0
# 1 0 -> 0
# 1 1 -> 1


X_and = np.array([[0, 0],
                 [0, 1],
                 [1, 0],
                 [1, 1]])
Y_and = np.array([[0, 0, 0, 1]])



In [28]:
X_i = np.tile(np.arange(0,4), 62)


In [29]:
np.random.shuffle(X_i)

In [30]:
len(X_i)

248

In [34]:
X = np.zeros((248, 2))
Y = np.zeros((248, 1))
print(X.shape)
print(Y.shape)

(248, 2)
(248, 1)


In [35]:

for i in range(len(X_i)):
    # print(i)
    # print(X_i[i])
    X[i] = X_and[X_i[i]]
    Y[i][0] = Y_and[0][X_i[i]]

In [39]:
X[:10]

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [40]:
Y[:10]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.]])

In [41]:
# Neural networks

X_in = X.T # (m,nx) -> (nx, m)
Y_in = Y.T # (m, 1) -> (1, m)


In [42]:
print(X_in.shape)
print(Y_in.shape)

(2, 248)
(1, 248)


In [43]:
layer_dims = np.array([2,2,1])

In [45]:
parameters, cost, w1_l, cost_l =  train(X_in, Y_in, layer_dims, learning_rate=0.075, iteration=1000)

Cost after iteration 0: 0.7473179428926656
Cost after iteration 100: 0.49496437443532315
Cost after iteration 200: 0.3848194605131475
Cost after iteration 300: 0.2643322981835189
Cost after iteration 400: 0.16383799976383281
Cost after iteration 500: 0.10220031728755286
Cost after iteration 600: 0.06832352338527324
Cost after iteration 700: 0.049215985674046656
Cost after iteration 800: 0.03774521387181944
Cost after iteration 900: 0.031134206408953095
Cost after iteration 999: 0.026735816610176592


In [46]:
print("Train Accuracy")
get_accuracy(parameters, X_in, Y_in)

Train Accuracy
Accuracy:  0.9999999999999996


np.float64(0.9999999999999996)

In [ ]:
test = np.array([[0],[0]]) # test input 0,0 -> op 0
predict(parameters, test)

array([[0.]])